const foods=[
 {id:1,name:'Masala Dosa',cat:'South Indian',price:65,desc:'Crisp dosa with spiced potato filling & chutneys.',tag:'Bestseller',img:'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=700&q=80'},
 {id:2,name:'Paneer Biryani',cat:'Rice Bowls',price:110,desc:'Fragrant basmati rice, paneer and house spices.',tag:'Popular',img:'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=700&q=80'},
 {id:3,name:'Classic Veg Burger',cat:'Quick Bites',price:75,desc:'Crispy patty, fresh lettuce and tangy sauce.',tag:'',img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=700&q=80'},
 {id:4,name:'Cold Coffee',cat:'Beverages',price:55,desc:'Chilled, creamy and made fresh to order.',tag:'Campus favourite',img:'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=700&q=80'},
 {id:5,name:'Veg Noodles',cat:'Quick Bites',price:80,desc:'Wok tossed noodles with crunchy vegetables.',tag:'',img:'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=700&q=80'},
 {id:6,name:'Idli & Vada',cat:'South Indian',price:50,desc:'Steamed idlis, crispy vada, sambar & chutney.',tag:'',img:'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&w=700&q=80'},
 {id:7,name:'Chole Bhature',cat:'North Indian',price:85,desc:'Fluffy bhature with slow-cooked spicy chickpeas.',tag:'',img:'https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=700&q=80'},
 {id:8,name:'Chocolate Brownie',cat:'Desserts',price:45,desc:'Warm chocolate brownie with a gooey centre.',tag:'Sweet pick',img:'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=700&q=80'},
 {id:9,name:'Veg Fried Rice',cat:'Rice Bowls',price:85,desc:'Wok-tossed rice with seasonal vegetables.',tag:'',img:'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=700&q=80'},
 {id:10,name:'Schezwan Momos',cat:'Quick Bites',price:70,desc:'Steamed dumplings with fiery dip.',tag:'Spicy',img:'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=700&q=80'},
 {id:11,name:'Veg Thali',cat:'North Indian',price:120,desc:'A wholesome meal with curry, dal, rice and roti.',tag:'Value meal',img:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=80'},
 {id:12,name:'Pav Bhaji',cat:'Quick Bites',price:65,desc:'Buttery pav with rich Mumbai-style bhaji.',tag:'',img:'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=700&q=80'},
 {id:13,name:'Lemon Rice',cat:'Rice Bowls',price:60,desc:'Tangy tempered rice with crunchy peanuts.',tag:'',img:'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=700&q=80'},
 {id:14,name:'Aloo Paratha',cat:'North Indian',price:55,desc:'Golden paratha served with curd and pickle.',tag:'',img:'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=700&q=80'},
 {id:15,name:'Filter Coffee',cat:'Beverages',price:30,desc:'Traditional strong South Indian filter coffee.',tag:'',img:'https://images.unsplash.com/photo-1521302080376-4f1d0cfe6f47?auto=format&fit=crop&w=700&q=80'},
 {id:16,name:'Mango Lassi',cat:'Beverages',price:45,desc:'A cool, creamy mango yoghurt drink.',tag:'',img:'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=700&q=80'},
 {id:17,name:'Samosa Chaat',cat:'Quick Bites',price:50,desc:'Crushed samosa, chutneys, curd and sev.',tag:'',img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=80'},
 {id:18,name:'Gulab Jamun',cat:'Desserts',price:35,desc:'Two warm dumplings in rose-cardamom syrup.',tag:'',img:'https://images.unsplash.com/photo-1666190092159-3171cf0fbb12?auto=format&fit=crop&w=700&q=80'},
 {id:19,name:'Veg Pizza',cat:'Quick Bites',price:105,desc:'Cheesy personal pizza with garden vegetables.',tag:'',img:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=700&q=80'},
 {id:20,name:'Curd Rice',cat:'South Indian',price:50,desc:'Cooling curd rice with tempering and pickle.',tag:'',img:'https://images.unsplash.com/photo-1630409351217-bc4fa6422075?auto=format&fit=crop&w=700&q=80'}];
let cart=JSON.parse(localStorage.getItem('quickbite-cart')||'[]'),active='All',pay='UPI';const $=s=>document.querySelector(s);const money=n=>`₹${n}`;
function save(){localStorage.setItem('quickbite-cart',JSON.stringify(cart))}function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function renderMenu(){let q=$('#search').value.toLowerCase();let items=foods.filter(f=>(active==='All'||f.cat===active)&&(`${f.name} ${f.cat}`).toLowerCase().includes(q));$('#food-grid').innerHTML=items.map(f=>{let inCart=cart.find(x=>x.id===f.id);return `<article class="food-card"><div class="food-image">${f.tag?`<span class="tag">${f.tag}</span>`:''}<img src="${f.img}" alt="${f.name}"></div><div class="food-info"><h3>${f.name}</h3><p>${f.desc}</p><div class="food-bottom"><b>${money(f.price)}</b>${inCart?`<button class="dish-remove" data-dish-remove="${f.id}">Remove</button>`:`<button class="add-btn" data-add="${f.id}" aria-label="Add ${f.name}">+</button>`}</div></div></article>`}).join('');$('#empty').hidden=!!items.length}
function renderCategories(){let cats=['All',...new Set(foods.map(f=>f.cat))];$('#categories').innerHTML=cats.map(c=>`<button class="category ${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('')}
function cartTotals(){let subtotal=cart.reduce((s,c)=>s+c.price*c.qty,0),fee=subtotal?10:0;return{subtotal,fee,total:subtotal+fee}}
function renderCart(){let t=cartTotals();$('#cart-count').textContent=cart.reduce((s,c)=>s+c.qty,0);$('#subtotal').textContent=money(t.subtotal);$('#fee').textContent=money(t.fee);$('#total').textContent=money(t.total);$('#pay-amount').textContent=money(t.total);$('#cart-items').innerHTML=cart.length?cart.map(c=>`<div class="cart-item"><img src="${c.img}" alt=""><div><h4>${c.name}</h4><p>${money(c.price)} each</p><div class="qty"><button data-qty="${c.id}" data-change="-1">−</button><b>${c.qty}</b><button data-qty="${c.id}" data-change="1">+</button></div></div><button class="remove" data-remove="${c.id}">×</button></div>`).join(''):'<p class="empty-cart">Your bag is empty.<br>Let’s find something tasty.</p>';$('#checkout-btn').disabled=!cart.length;$('#checkout-btn').style.opacity=cart.length?'1':'.5'}
function add(id){let f=foods.find(x=>x.id===id),line=cart.find(x=>x.id===id);line?line.qty++:cart.push({...f,qty:1});save();renderCart();renderMenu();toast(`${f.name} added to Bhojan`)}
function toggle(id){$(id).classList.toggle('open')}function closeAll(){['#cart-panel','#checkout-modal','#success-modal','#menu-modal'].forEach(id=>$(id).classList.remove('open'));$('#scrim').classList.remove('open')}
renderCategories();renderMenu();renderCart();
$('#enter-site').onclick=()=>{$('#page-turn').classList.add('flip');$('#welcome-screen').classList.add('hide');$('#app').classList.add('live');setTimeout(()=>$('#welcome-screen').remove(),1200)};
$('#browse-btn').onclick=()=>$('#menu').scrollIntoView({behavior:'smooth'});$('#search').oninput=renderMenu;$('#categories').onclick=e=>{if(!e.target.dataset.cat)return;active=e.target.dataset.cat;renderCategories();renderMenu()};$('#food-grid').onclick=e=>{if(e.target.dataset.add)add(+e.target.dataset.add);if(e.target.dataset.dishRemove){cart=cart.filter(x=>x.id!==+e.target.dataset.dishRemove);save();renderCart();renderMenu();toast('Dish removed from Bhojan')}};
$('#cart-btn').onclick=()=>{$('#cart-panel').classList.add('open');$('#scrim').classList.add('open')};$('#scrim').onclick=closeAll;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeAll);$('#cart-items').onclick=e=>{if(e.target.dataset.remove){cart=cart.filter(x=>x.id!==+e.target.dataset.remove)}if(e.target.dataset.qty){let c=cart.find(x=>x.id===+e.target.dataset.qty);c.qty+=+e.target.dataset.change;if(c.qty<1)cart=cart.filter(x=>x.id!==c.id)}save();renderCart()};
$('#checkout-btn').onclick=()=>{if(!cart.length)return;$('#cart-panel').classList.remove('open');$('#scrim').classList.remove('open');$('#checkout-modal').classList.add('open')};document.querySelectorAll('.pay-option').forEach(b=>b.onclick=()=>{pay=b.dataset.pay;document.querySelectorAll('.pay-option').forEach(x=>x.classList.toggle('selected',x===b));$('#payment-fields').innerHTML=pay==='UPI'?'<label>UPI ID<input id="upi" required pattern="[\\w.-]+@[\\w.-]+" title="Enter a valid UPI ID, e.g. name@bank" placeholder="name@bank"></label>':'<label>Card number<input required inputmode="numeric" pattern="[0-9 ]{16,19}" title="Enter a valid 16 digit card number" placeholder="1234 5678 9012 3456"></label><div class="form-row"><label>Expiry<input required pattern="(0[1-9]|1[0-2])\\/[0-9]{2}" title="Use MM/YY" placeholder="MM/YY"></label><label>CVV<input required inputmode="numeric" pattern="[0-9]{3}" title="Use a 3 digit CVV" placeholder="123"></label></div>'});
$('#checkout-form').onsubmit=e=>{e.preventDefault();let number=`QB-${Math.floor(1000+Math.random()*9000)}`;let orders=JSON.parse(localStorage.getItem('quickbite-orders')||'[]');orders.unshift({number,total:cartTotals().total,name:$('#name').value,time:$('#pickup').value,date:new Date().toLocaleDateString()});localStorage.setItem('quickbite-orders',JSON.stringify(orders));$('#order-number').textContent=number;cart=[];save();renderCart();renderOrders();$('#checkout-modal').classList.remove('open');$('#success-modal').classList.add('open')};
function renderOrders(){let o=JSON.parse(localStorage.getItem('quickbite-orders')||'[]');$('#order-history').innerHTML=o.length?o.slice(0,3).map(x=>`<div class="order-row"><b>${x.number} · ${money(x.total)}</b>Preparing · ${x.time}</div>`).join(''):'<p>You haven’t placed an order yet. Your next favourite is waiting on the menu.</p>'}renderOrders();
$('#menu-book-btn').onclick=()=>$('#menu-modal').classList.add('open');$('#open-book').onclick=()=>{$('.book-cover').classList.add('open')};$('#turn-page').onclick=()=>{let l=foods.slice(4,8),r=foods.slice(0,4);$('#book-left').innerHTML=l.map(f=>`<div class="book-item"><span>${f.name}<small>${f.cat}</small></span><b>${money(f.price)}</b></div>`).join('');$('#book-right').innerHTML=r.map(f=>`<div class="book-item"><span>${f.name}<small>${f.cat}</small></span><b>${money(f.price)}</b></div>`).join('');toast('A fresh page of favourites')};$('#turn-page').click();
let authMode='login',selectedStars=0;const accountsKey='quickbite-accounts';
function setAuthMode(mode){authMode=mode;$('#auth-copy').textContent=mode==='login'?'Log in using your official KLH email address.':'Create your student QuickBite account with your KLH email.';$('#auth-submit').innerHTML=mode==='login'?'Log in <b>→</b>':'Create account <b>→</b>';$('#auth-switch').innerHTML=mode==='login'?'New to QuickBite? <button id="switch-auth">Create an account</button>':'Already registered? <button id="switch-auth">Log in instead</button>';$('#switch-auth').onclick=()=>setAuthMode(authMode==='login'?'signup':'login')}
function finishAuth(email){localStorage.setItem('quickbite-user',email);$('#account-btn').innerHTML=`👤 <span>Hi, ${email.split('@')[0]}</span>`;$('#auth-gate').classList.add('hide');setTimeout(()=>$('#auth-gate').remove(),450)}
$('#auth-form').onsubmit=e=>{e.preventDefault();let email=$('#auth-email').value.trim().toLowerCase(),password=$('#auth-password').value,error=$('#auth-error');error.textContent='';if(!email.endsWith('@klh.edu.in')){error.textContent='Invalid login. Please use your official @klh.edu.in email address.';return}let accounts=JSON.parse(localStorage.getItem(accountsKey)||'{}');if(authMode==='signup'){if(accounts[email]){error.textContent='This Gmail already exists. Please log in instead.';return}accounts[email]={password};localStorage.setItem(accountsKey,JSON.stringify(accounts));finishAuth(email);return}if(!accounts[email]){error.textContent='No account found for this KLH email. Please create an account.';return}if(accounts[email].password!==password){error.textContent='Incorrect password. Please try again.';return}finishAuth(email)};setAuthMode('login');
function renderReviews(){let reviews=JSON.parse(localStorage.getItem('quickbite-reviews')||'[]');$('#review-list').innerHTML=reviews.length?reviews.slice(0,5).map(r=>`<div class="review"><b>${r.food}</b><span>${'★'.repeat(r.stars)}</span><p>${r.text}</p><small>${r.author}</small></div>`).join(''):'<p class="muted">No reviews yet. Be the first to rate a bite.</p>'}
$('#rating-food').innerHTML=foods.map(f=>`<option value="${f.name}">${f.name}</option>`).join('');$('#stars').onclick=e=>{if(!e.target.dataset.star)return;selectedStars=+e.target.dataset.star;document.querySelectorAll('#stars button').forEach(b=>b.classList.toggle('active',+b.dataset.star<=selectedStars))};$('#rating-form').onsubmit=e=>{e.preventDefault();if(!selectedStars){toast('Please choose a star rating first');return}let reviews=JSON.parse(localStorage.getItem('quickbite-reviews')||'[]');reviews.unshift({food:$('#rating-food').value,stars:selectedStars,text:$('#review-text').value,author:(localStorage.getItem('quickbite-user')||'KLH Student').split('@')[0]});localStorage.setItem('quickbite-reviews',JSON.stringify(reviews));$('#rating-form').reset();selectedStars=0;document.querySelectorAll('#stars button').forEach(b=>b.classList.remove('active'));renderReviews();toast('Thanks for sharing your review!')};renderReviews();
function renderComplaints(){let complaints=JSON.parse(localStorage.getItem('quickbite-complaints')||'[]');$('#complaint-list').innerHTML=complaints.length?complaints.slice(0,8).map(c=>`<article class="complaint">${c.text}<small>Submitted by ${c.author} · ${c.date}</small></article>`).join(''):'<p class="muted">No community complaints have been submitted.</p>'}$('#complaint-form').onsubmit=e=>{e.preventDefault();let complaints=JSON.parse(localStorage.getItem('quickbite-complaints')||'[]');complaints.unshift({text:$('#complaint-text').value,author:(localStorage.getItem('quickbite-user')||'KLH Student').split('@')[0],date:new Date().toLocaleDateString()});localStorage.setItem('quickbite-complaints',JSON.stringify(complaints));$('#complaint-form').reset();renderComplaints();toast('Complaint shared with the community and canteen team.')};renderComplaints();
const originalRenderOrders=renderOrders;renderOrders=function(){let o=JSON.parse(localStorage.getItem('quickbite-orders')||'[]');$('#order-history').innerHTML=o.length?o.slice(0,3).map(x=>`<div class="order-row"><b>${x.number} · ${money(x.total)}</b>Preparing · estimated ${x.time.includes('ASAP')?'15–20 minutes':x.time}</div>`).join(''):'<p>You haven’t placed an order yet. Your next favourite is waiting on the menu.</p>'};renderOrders();
document.body.classList.add('locked');
const themeButton=document.createElement('button');themeButton.className='theme-btn';themeButton.type='button';themeButton.innerHTML='☾ <span>Gold</span>';document.querySelector('.nav-actions').prepend(themeButton);themeButton.onclick=()=>{document.body.classList.toggle('gold-theme');themeButton.innerHTML=document.body.classList.contains('gold-theme')?'☀ <span>Light</span>':'☾ <span>Gold</span>';localStorage.setItem('quickbite-theme',document.body.classList.contains('gold-theme')?'gold':'light')};if(localStorage.getItem('quickbite-theme')==='gold')themeButton.click();
const authDone=finishAuth;finishAuth=function(email){document.body.classList.remove('locked');authDone(email)};
document.querySelector('#rating-form textarea').insertAdjacentHTML('beforebegin','<div class="emoji-row" id="emoji-row"><button type="button" data-emoji="😋">😋</button><button type="button" data-emoji="😍">😍</button><button type="button" data-emoji="😄">😄</button><button type="button" data-emoji="🤩">🤩</button><button type="button" data-emoji="😐">😐</button></div>');let reviewEmoji='';$('#emoji-row').onclick=e=>{if(!e.target.dataset.emoji)return;reviewEmoji=e.target.dataset.emoji;document.querySelectorAll('#emoji-row button').forEach(b=>b.classList.toggle('selected',b===e.target))};
const oldReviewRender=renderReviews;renderReviews=function(){let reviews=JSON.parse(localStorage.getItem('quickbite-reviews')||'[]');$('#review-list').innerHTML=reviews.length?reviews.slice(0,5).map(r=>`<div class="review"><b>${r.food} ${r.emoji||''}</b><span>${'★'.repeat(r.stars)}</span><p>${r.text}</p><small>${r.author}</small></div>`).join(''):'<p class="muted">No reviews yet. Be the first to rate a bite.</p>'};const oldRatingSubmit=$('#rating-form').onsubmit;$('#rating-form').onsubmit=e=>{e.preventDefault();if(!selectedStars){toast('Please choose a star rating first');return}let reviews=JSON.parse(localStorage.getItem('quickbite-reviews')||'[]');reviews.unshift({food:$('#rating-food').value,stars:selectedStars,text:$('#review-text').value,emoji:reviewEmoji,author:(localStorage.getItem('quickbite-user')||'KLH Student').split('@')[0]});localStorage.setItem('quickbite-reviews',JSON.stringify(reviews));$('#rating-form').reset();selectedStars=0;reviewEmoji='';document.querySelectorAll('#stars button,#emoji-row button').forEach(b=>b.classList.remove('active','selected'));renderReviews();toast('Thanks for sharing your review!')};renderReviews();
document.querySelector('#complaints').insertAdjacentHTML('afterend','<section class="booking" id="booking"><div><p class="eyebrow">• TABLE RESERVATIONS</p><h2>A table,<br><i>right on time.</i></h2><p>Reserve a canteen table for groups. Peak slots cost a little more and holidays are unavailable.</p><div class="rush-note"><b>Rush hours</b><span>12:30–2:30 PM · ₹30 table fee</span><span>Other slots · ₹15 table fee</span></div><div class="holiday-note">Canteen closed: Sundays and university-declared holidays.</div></div><form id="booking-form" class="booking-form"><label>Date<input id="booking-date" required type="date"></label><label>Time<select id="booking-time" required><option value="">Select a time</option><option>10:00 AM</option><option>11:00 AM</option><option>12:30 PM</option><option>1:00 PM</option><option>1:30 PM</option><option>2:00 PM</option><option>2:30 PM</option><option>3:30 PM</option><option>4:30 PM</option><option>5:30 PM</option></select></label><label>Guests<select id="booking-guests"><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5 guests</option><option>6 guests</option></select></label><div class="booking-price" id="booking-price">Select a date and time</div><p class="booking-error" id="booking-error"></p><button class="orange-button full">Reserve table <b>→</b></button></form></section>');
const dateInput=$('#booking-date'),timeInput=$('#booking-time'),bookingPrice=$('#booking-price'),holidays=['2026-08-15','2026-08-27','2026-10-02','2026-10-19','2026-10-20','2026-10-21','2026-12-25'];dateInput.min=new Date().toISOString().slice(0,10);function tableFee(){if(!dateInput.value||!timeInput.value){bookingPrice.textContent='Select a date and time';return 0}let rush=['12:30 PM','1:00 PM','1:30 PM','2:00 PM','2:30 PM'].includes(timeInput.value),fee=rush?30:15;bookingPrice.innerHTML=`Table reservation fee <b>${money(fee)}</b>${rush?' <span>Rush-hour rate</span>':''}`;return fee}dateInput.onchange=tableFee;timeInput.onchange=tableFee;$('#booking-form').onsubmit=e=>{e.preventDefault();let d=new Date(`${dateInput.value}T12:00:00`),error=$('#booking-error');error.textContent='';if(d.getDay()===0||holidays.includes(dateInput.value)){error.textContent='This is a canteen holiday. Please choose another date.';return}if(!timeInput.value){error.textContent='Please choose a valid service time.';return}let bookings=JSON.parse(localStorage.getItem('quickbite-bookings')||'[]'),id=`TB-${Math.floor(1000+Math.random()*9000)}`;bookings.unshift({id,date:dateInput.value,time:timeInput.value,guests:$('#booking-guests').value,fee:tableFee()});localStorage.setItem('quickbite-bookings',JSON.stringify(bookings));toast(`Table reserved! Your booking ID is ${id}`);$('#booking-form').reset();bookingPrice.textContent='Select a date and time'};
// Landing → KLH login → app transition
$('#enter-site').onclick=()=>{document.body.classList.add('locked');$('#auth-gate').classList.add('open')};
finishAuth=function(email){localStorage.setItem('quickbite-user',email);$('#account-btn').innerHTML=`👤 <span>Hi, ${email.split('@')[0]}</span>`;$('#page-turn').innerHTML='<div class="klh-transition"><img src="file:///C:/Users/Admin/AppData/Local/Temp/codex-clipboard-c36fb7bc-19d2-43c9-bd0f-6b03b41657dc.png" alt="KLH"></div>' ;$('#page-turn').classList.add('flip');$('#auth-gate').classList.remove('open');$('#welcome-screen').classList.add('hide');$('#app').classList.add('live');document.body.classList.remove('locked');setTimeout(()=>{$('#welcome-screen').remove();$('#auth-gate').remove();$('#page-turn').innerHTML=''},1200);showPage('home')};
// Sidebar pages
document.querySelector('.app').insertAdjacentHTML('afterbegin','<aside class="sidebar" id="sidebar"><a class="side-brand" href="#"><span>Q</span></a><button class="side-link active" data-page="home">⌂ <small>Home</small></button><button class="side-link" data-page="dishes">☰ <small>Dishes</small></button><button class="side-link" data-page="card">▤ <small>Menu card</small></button><button class="side-link" data-page="orders">◷ <small>Orders</small></button><button class="side-link" data-page="ratings">★ <small>Ratings</small></button><button class="side-link" data-page="booking">▦ <small>Tables</small></button><button class="side-link" data-page="complaints">! <small>Voice</small></button></aside>');
const pageSections={home:['.hero','#how'],dishes:['#menu'],orders:['#orders'],ratings:['#feedback'],booking:['#booking'],complaints:['#complaints']};function showPage(page){Object.values(pageSections).flat().forEach(s=>$(s).style.display='none');if(page==='card'){$('#menu-modal').classList.add('open')}else{pageSections[page].forEach(s=>$(s).style.display='');window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}$('#sidebar').onclick=e=>{let b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page)};
// Receipt download after successful payment
$('#order-number').insertAdjacentHTML('afterend','<button class="receipt-btn" id="receipt-btn">⇩ Download receipt</button>');let receiptData=null;$('#checkout-form').onsubmit=e=>{e.preventDefault();let number=`QB-${Math.floor(1000+Math.random()*9000)}`,totals=cartTotals(),items=cart.map(x=>({...x}));let orders=JSON.parse(localStorage.getItem('quickbite-orders')||'[]');orders.unshift({number,total:totals.total,name:$('#name').value,time:$('#pickup').value,date:new Date().toLocaleDateString()});localStorage.setItem('quickbite-orders',JSON.stringify(orders));receiptData={number,items,total:totals.total,name:$('#name').value,time:$('#pickup').value,date:new Date().toLocaleString()};$('#order-number').textContent=number;cart=[];save();renderCart();renderOrders();$('#checkout-modal').classList.remove('open');$('#success-modal').classList.add('open')};$('#receipt-btn').onclick=()=>{if(!receiptData){toast('Place an order to create a receipt.');return}let text=`QUICKBITE · KLH UNIVERSITY\n--------------------------------\nReceipt: ${receiptData.number}\nStudent: ${receiptData.name}\nDate: ${receiptData.date}\nPickup: ${receiptData.time}\n--------------------------------\n${receiptData.items.map(i=>`${i.name} x${i.qty}  ₹${i.price*i.qty}`).join('\n')}\n--------------------------------\nTOTAL PAID: ₹${receiptData.total}\n\nThank you for choosing QuickBite!`;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download=`${receiptData.number}-receipt.txt`;a.click();URL.revokeObjectURL(a.href)};
finishAuth=function(email){localStorage.setItem('quickbite-user',email);$('#account-btn').innerHTML=`👤 <span>Hi, ${email.split('@')[0]}</span>`;$('#page-turn').innerHTML='<div class="klh-transition"><img src="file:///C:/Users/Admin/AppData/Local/Temp/codex-clipboard-c36fb7bc-19d2-43c9-bd0f-6b03b41657dc.png" alt="KLH"></div>' ;$('#page-turn').classList.add('flip');$('#auth-gate').classList.remove('open');$('#welcome-screen').classList.add('hide');$('#app').classList.add('live');document.body.classList.remove('locked');setTimeout(()=>{$('#welcome-screen').remove();$('#auth-gate').remove();$('#page-turn').innerHTML=''},3200);showPage('home')};
// Restaurant-style dashboard, profile and menu-card experience
foods.push(
 {id:21,name:'Cheese Corn Sandwich',cat:'Quick Bites',price:60,desc:'Toasted sandwich with sweet corn and cheese.',tag:'',img:'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=700&q=80'},
 {id:22,name:'Veg Manchurian',cat:'Quick Bites',price:90,desc:'Crisp vegetable balls in a savoury sauce.',tag:'',img:'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=700&q=80'},
 {id:23,name:'Rajma Chawal',cat:'North Indian',price:90,desc:'Comforting kidney bean curry with steamed rice.',tag:'',img:'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=700&q=80'},
 {id:24,name:'Tomato Soup',cat:'Beverages',price:45,desc:'Warm creamy tomato soup with croutons.',tag:'',img:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=700&q=80'},
 {id:25,name:'Fruit Salad',cat:'Desserts',price:50,desc:'Fresh seasonal fruit with a honey drizzle.',tag:'',img:'https://images.unsplash.com/photo-1568158879083-c42860933ed7?auto=format&fit=crop&w=700&q=80'},
 {id:26,name:'Veg Pulao',cat:'Rice Bowls',price:75,desc:'Lightly spiced basmati rice and vegetables.',tag:'',img:'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=700&q=80'},
 {id:27,name:'Onion Uttapam',cat:'South Indian',price:70,desc:'Soft rice pancake loaded with onions.',tag:'',img:'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=700&q=80'},
 {id:28,name:'Vanilla Milkshake',cat:'Beverages',price:60,desc:'Classic thick shake with vanilla ice cream.',tag:'',img:'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=700&q=80'}
);renderCategories();renderMenu();$('#rating-food').innerHTML=foods.map(f=>`<option value="${f.name}">${f.name}</option>`).join('');
document.querySelector('.brand.klh-brand').innerHTML='<img class="header-klh" src="file:///C:/Users/Admin/AppData/Local/Temp/codex-clipboard-c36fb7bc-19d2-43c9-bd0f-6b03b41657dc.png" alt="KLH University"><strong>quickbite</strong>';
document.querySelector('.sidebar').remove();document.querySelector('.app').insertAdjacentHTML('afterbegin','<aside class="sidebar" id="sidebar"><img class="sidebar-logo" src="file:///C:/Users/Admin/AppData/Local/Temp/codex-clipboard-c36fb7bc-19d2-43c9-bd0f-6b03b41657dc.png" alt="KLH"><button class="side-link active" data-page="home">⌂<small>Home</small></button><button class="side-link" data-page="dishes">☰<small>Dishes</small></button><button class="side-link" data-page="card">▤<small>Menu card</small></button><button class="side-link" data-page="orders">◷<small>Orders</small></button><button class="side-link" data-page="ratings">★<small>Ratings</small></button><button class="side-link" data-page="booking">▦<small>Tables</small></button><button class="side-link" data-page="account">◉<small>Account</small></button><button class="side-link" data-page="contact">✉<small>Contact</small></button><button class="side-link logout-link" data-page="logout">↪<small>Logout</small></button></aside>');
document.querySelector('#booking').insertAdjacentHTML('afterend','<section class="account-page" id="account-page"><p class="eyebrow">• MY ACCOUNT</p><h2>Your KLH <i>profile.</i></h2><div class="account-card"><div class="account-avatar">👤</div><div><b id="profile-name">KLH Student</b><p id="profile-email">student@klh.edu.in</p></div></div><form id="reset-form" class="reset-form"><h3>Reset password</h3><label>Current password<input id="current-pass" required type="password" minlength="4"></label><label>New password<input id="new-pass" required type="password" minlength="4"></label><p class="account-message" id="account-message"></p><button class="orange-button">Update password</button></form></section><section class="contact-page" id="contact-page"><p class="eyebrow">• CONTACT QUICKBITE</p><h2>We’re here to <i>help.</i></h2><div class="contact-grid"><article><span>☎</span><h3>Canteen desk</h3><p>+91 40 1234 5678<br>Mon–Sat · 9 AM–8 PM</p></article><article><span>✉</span><h3>Email support</h3><p>quickbite@klh.edu.in<br>Response within one working day</p></article><article><span>⌖</span><h3>Find us</h3><p>KLH University<br>Main Canteen, Ground Floor</p></article></div></section>');
const specials=[['🍕','Veg Pizza'],['🍛','Paneer Biryani'],['🥪','Cheese Corn Sandwich'],['🍜','Veg Noodles'],['🍰','Chocolate Brownie'],['🥤','Mango Lassi']];document.querySelector('.hero').insertAdjacentHTML('beforeend','<div class="home-dashboard"><button class="book-home" id="book-home">Book a table</button><h2>Today’s specials</h2><div class="specials-row" id="specials-row"></div><h3>Explore food categories</h3><div class="home-categories"><button data-go="South Indian">🍛<span>South Indian</span></button><button data-go="Quick Bites">🍜<span>Quick Bites</span></button><button data-go="Desserts">🍰<span>Desserts</span></button></div></div>');
let specialOffset=new Date().getDate()%specials.length;function renderSpecials(){let shown=[0,1,2].map(i=>specials[(specialOffset+i)%specials.length]);$('#specials-row').innerHTML=shown.map(s=>`<div><span>${s[0]}</span><b>${s[1]}</b></div>`).join('')}renderSpecials();setInterval(()=>{specialOffset=(specialOffset+1)%specials.length;renderSpecials()},7000);$('#book-home').onclick=()=>showPage('booking');document.querySelector('.home-categories').onclick=e=>{let b=e.target.closest('[data-go]');if(!b)return;active=b.dataset.go;renderCategories();renderMenu();showPage('dishes')};
const mainSections={home:['.hero'],dishes:['#menu'],orders:['#orders'],ratings:['#feedback'],booking:['#booking'],account:['#account-page'],contact:['#contact-page']};showPage=function(page){if(page==='logout'){localStorage.removeItem('quickbite-user');location.reload();return}Object.values(mainSections).flat().forEach(s=>$(s).style.display='none');$('#menu-modal').classList.remove('open');if(page==='card'){openMenuCard()}else{mainSections[page].forEach(s=>$(s).style.display='');window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page))};$('#sidebar').onclick=e=>{let b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page)};
function openMenuCard(){let cats=['All',...new Set(foods.map(f=>f.cat))],book=$('.book-pages');book.innerHTML=`<div class="book-page menu-index"><p class="eyebrow">• KLH MAIN CANTEEN</p><h3>Menu <i>card</i></h3><p class="page-intro">Choose a section to browse today’s dishes.</p><div class="book-tabs">${cats.map(c=>`<button data-book-cat="${c}">${c}</button>`).join('')}</div></div><div class="book-page book-menu-list"><p class="eyebrow">• ALL DAY MENU</p><div id="book-items"></div></div>`;book.onclick=e=>{let b=e.target.closest('[data-book-cat]');if(!b)return;document.querySelectorAll('[data-book-cat]').forEach(x=>x.classList.toggle('active',x===b));let list=b.dataset.bookCat==='All'?foods:foods.filter(f=>f.cat===b.dataset.bookCat);$('#book-items').innerHTML=list.map(f=>`<div class="book-item"><span>${f.name}<small>${f.desc}</small></span><b>${money(f.price)}</b></div>`).join('')};book.querySelector('button').click();$('.book-cover').classList.add('open');$('#menu-modal').classList.add('open')}
$('#menu-book-btn').onclick=openMenuCard;
function refreshProfile(){let email=localStorage.getItem('quickbite-user')||'student@klh.edu.in';$('#profile-email').textContent=email;$('#profile-name').textContent=email.split('@')[0]||'KLH Student'}refreshProfile();$('#reset-form').onsubmit=e=>{e.preventDefault();let email=localStorage.getItem('quickbite-user'),accounts=JSON.parse(localStorage.getItem(accountsKey)||'{}'),msg=$('#account-message');if(!email||!accounts[email]||accounts[email].password!==$('#current-pass').value){msg.textContent='Current password is incorrect.';return}accounts[email].password=$('#new-pass').value;localStorage.setItem(accountsKey,JSON.stringify(accounts));msg.textContent='Password updated successfully.';e.target.reset()};
// Dedicated full-page menu card (no split overlay or page background)
document.querySelector('.app main').insertAdjacentHTML('beforeend','<section class="menu-card-page" id="menu-card-page"><div class="menu-card-top"><div><p class="eyebrow">• KLH UNIVERSITY · MAIN CANTEEN</p><h2>Menu <i>card</i></h2><p>Browse each section of today’s all-day menu.</p></div><button class="card-back" id="card-back">← Back to home</button></div><div class="menu-card-layout"><aside class="menu-section-nav" id="menu-section-nav"></aside><div class="menu-card-items"><p class="eyebrow" id="menu-card-kicker">• ALL DISHES</p><div id="menu-card-items"></div></div></div></section>');
function renderFullMenu(category='All'){let cats=['All',...new Set(foods.map(f=>f.cat))];$('#menu-section-nav').innerHTML=cats.map(c=>`<button class="${c===category?'active':''}" data-full-cat="${c}">${c}</button>`).join('');let items=category==='All'?foods:foods.filter(f=>f.cat===category);$('#menu-card-kicker').textContent=`• ${category.toUpperCase()}`;$('#menu-card-items').innerHTML=items.map(f=>`<article class="full-menu-item"><img src="${f.img}" alt="${f.name}"><div><h3>${f.name}</h3><p>${f.desc}</p></div><b>${money(f.price)}</b></article>`).join('')};renderFullMenu();$('#menu-section-nav').onclick=e=>{let b=e.target.closest('[data-full-cat]');if(b)renderFullMenu(b.dataset.fullCat)};$('#card-back').onclick=()=>showPage('home');
const cleanSections={home:['.hero'],dishes:['#menu'],orders:['#orders'],ratings:['#feedback'],booking:['#booking'],account:['#account-page'],contact:['#contact-page'],card:['#menu-card-page']};showPage=function(page){if(page==='logout'){localStorage.removeItem('quickbite-user');location.reload();return}Object.values(cleanSections).flat().forEach(s=>$(s).style.display='none');$('#menu-modal').classList.remove('open');cleanSections[page].forEach(s=>$(s).style.display='');document.body.classList.toggle('menu-focus',page==='card');window.scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.page===page))};
